# Basic settings
title: "Mengxin Pan"
description: "I will join the Department of Geography at Simon Fraser University as a tenure-track assistant professor in Jan 2025."
url: "https://panmengxin.github.io/mengxin_pan/"
baseurl: ""
email: "mengxin_pan@sfu.ca"

# Build settings
markdown: kramdown
encoding: utf-8
timezone: America/Vancouver

# Plugin settings
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Navigation (empty arrays)
navigation_header: []
navigation_footer: []

# Theme settings
logo: ""  # Empty string instead of empty array


# SEO settings
title: "Mengxin Pan"
description: "Climate scientist, Assistant professor at Simon Fraser University"
author: "Mengxin Pan"
google_site_verification: 950807  # If you want to verify with Google

# Add more detailed SEO tags
seo:
  name: "Mengxin Pan"
  type: Person
  links:
    - https://panmengxin.github.io/mengxin_pan/
